---
version: '3.9'

services:
  backend:
    image: tfonferm/ai35_weather_forecast:backend-latest
    volumes:
    ports:
      - "18000:8000"
    networks:
      - service_network

  frontend:
    image: tfonferm/ai35_weather_forecast:frontend-latest
    depends_on:
      - backend
    ports:
      - "18501:8501"
    networks:
      - service_network
    environment:
      - BACKEND_HOST=backend
      - BACKEND_PORT=8000

networks:
  service_network:
    driver: bridge
