---
name: build image, push to dockerhub, deploy on vm

on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - '*'
    tags:
      - '*'
jobs:
  backend-push_to_registry:
    name: backend build and push
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v4

      - name: login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_PASSWORD}}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            tfonferm/ai35_weather_forecast
          tags: |
                type=raw,value=backend-latest
                type=sha,prefix=backend-sha-
                type=ref,event=tag,prefix=backend-

      - name: build and push docker image to registry
        uses: docker/build-push-action@v5
        with:
          context: .
          file: service/backend/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}

  frontend-push_to_registry:
    name: frontend build and push
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v4

      - name: login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_PASSWORD}}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            tfonferm/ai35_weather_forecast
          tags: |
                type=raw,value=frontend-latest
                type=sha,prefix=frontend-sha-
                type=ref,event=tag,prefix=frontend-

      - name: build and push docker image to registry
        uses: docker/build-push-action@v5
        with:
          context: .
          file: service/frontend/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}

  deploy:
    name: Deploy service to host
    runs-on: ubuntu-latest
    if: ${{ startsWith(github.ref, 'refs/tags/') }}
    needs:
      - backend-push_to_registry
      - frontend-push_to_registry

    steps:
      - name: checkout repository
        uses: actions/checkout@v4

      - name: Copy docker-compose
        uses: appleboy/scp-action@v0.1.7
        with:
          host: 84.201.145.245
          username: weather
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          source: "service/docker-compose/docker-compose.yml"
          target: ~/weather

      - name: Pull images, copy compose
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: 84.201.145.245
          username: weather
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd ~/weather/service/docker-compose/
            docker compose pull
            docker compose down
            docker compose up -d
          